/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Links } from './links';


export interface EntityModelCanUser { 
    admin?: number;
    datec?: Date;
    datelastlogin?: Date;
    datepreviouslogin?: Date;
    egroupwareId?: Date;
    email?: string;
    entity?: number;
    firstname?: string;
    lang?: string;
    ldapSid?: string;
    links?: Links;
    login?: string;
    moduleComm?: number;
    moduleCompta?: number;
    name?: string;
    note?: string;
    officeFax?: string;
    officePhone?: string;
    pass?: string;
    passCrypted?: string;
    passTemp?: string;
    phenixLogin?: string;
    phenixPass?: string;
    photo?: string;
    rowid?: number;
    statut?: number;
    tms?: Date;
    userMobile?: string;
    webcalLogin?: string;
}
